# Upload the raw CSV file for Execution Cleaning part

In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("../data/raw/European_Bank.csv")
df.head()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [15]:
# Droping non-usable columns
df.drop(['Surname'], axis=1, inplace=True)

In [16]:
df.head()

,Year,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [17]:
# Checking Duplicate data
df.duplicated().sum()

np.int64(0)

In [18]:
df.isnull().sum()

Year               0
CustomerId         0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(2)
memory usage: 1015.8+ KB

### Turning Male/Female count in number for better analysis

In [20]:
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})

In [21]:
df.head(10)

,Year,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,2025,15574012,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,2025,15592531,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,2025,15656148,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1
8,2025,15792365,501,France,1,44,4,142051.07,2,0,1,74940.50,0
9,2025,15592389,684,France,1,27,2,134603.88,1,1,1,71725.73,0

## Exporting the clean CSV data

In [22]:
df.to_csv("../data/processed/cleaned_data.csv", index=False)

## Data Cleaning Summary

- Removed Surname column
- Checked duplicates: `Zero [0]`
- Missing values: `Zero [0]`
- Encoded Gender column